### ISSUE TITLE
Build on Node 14

### ISSUE THREAD

**Issue by alexkrolick** [bretcope/node-gc-profiler#17]
Similar to https://github.com/bretcope/node-gc-profiler/pull/15/, it looks like `gc-profiler` doesn't run on the latest version of Node (14). Can a new version be published for it? Might also be a good idea to add the `engines` field to `package.json` to warn about this at install time.

**Comment by orgads** [comment]
It builds just fine here. Tested on Windows and Linux.

I fixed some deprecation warnings, and created a new tag anyway.

**Comment by alexkrolick** [comment]
Thanks - I think the issue is something in my CI job is changing the version after build, which then causes an error saying the module was compiled with a different version of node.
