### ISSUE TITLE
Compacted flag never set?

### ISSUE THREAD

**Issue by seti123** [bretcope/node-gc-profiler#5]
I use gc-profiler but have never seen "compacted" flag set to true  - could you pls. confirm that this flag is working. And on which conditions it might be set? It might be a bug.

**Comment by bretcope** [comment]
It appears that v8 is currently [not using the kGCCallbackFlagCompacted flag](https://github.com/v8/v8-git-mirror/search?utf8=%E2%9C%93&q=kGCCallbackFlagCompacted) at all. It's likely that previous versions did.

There's nothing I can do about it, but I'll make a note of it in the readme, and perhaps I should create a new interface and bump this library a major version.

**Comment by bretcope** [comment]
After a little bit more investigating, it was removed in v8 `3.6.5` ([see diff](https://github.com/v8/v8-git-mirror/commit/c3b670ff19220959730d7886892bc4beb95d2eba#diff-bec250dfb499abc13cc73aa4e5d87f27L785)), which means it hasn't worked for quite some time.

**Comment by bretcope** [comment]
New version published as `1.2.0` and readme updated. I decided that this was only a minor breaking change, since `compacted` was always false anyway.

**Comment by megastef** [comment]
Thx for looking into it.
